[keyboard]
name = "cornix dongle basic"
product_name = "cornix dongle basic"
vendor_id = 0x4c4b
product_id = 0x5200
manufacturer = "RMK"
chip = "nrf52840"

[layout]
rows = 1
cols = 1
layers = 1
keymap = [
    [["No"]]
]

[matrix]
row_pins = ["P0_29"]
col_pins = ["P0_31"]

[ble]
enabled = true

[host]
vial_enabled = true

[storage]
enabled = true
