[meta]
family = "corne"
source = "continuum/matrix/corne.toml"

[layout]
rows = 4
cols = 12
slots = [
  ["__", "LT4", "LT3", "LT2", "LT1", "LT0", "RT0", "RT1", "RT2", "RT3", "RT4", "__"],
  ["__", "LM4", "LM3", "LM2", "LM1", "LM0", "RM0", "RM1", "RM2", "RM3", "RM4", "__"],
  ["__", "LB4", "LB3", "LB2", "LB1", "LB0", "RB0", "RB1", "RB2", "RB3", "RB4", "__"],
  ["__", "__", "__", "__", "LH1", "LH0", "RH0", "RH1", "__", "__", "__", "__"],
]
