use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use regex::Regex;
use serde::de::DeserializeOwned;
use serde::Deserialize;
use toml::Value;

#[derive(Debug, Deserialize)]
struct CoreToml {
    core: CoreSection,
    layers: HashMap<String, Value>,
}

#[derive(Debug, Deserialize)]
struct CoreSection {
    slot_order: Vec<String>,
    layer_order: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct MatrixToml {
    meta: MatrixMeta,
    layout: MatrixLayout,
}

#[derive(Debug, Deserialize)]
struct MatrixMeta {
    family: String,
}

#[derive(Debug, Deserialize)]
struct MatrixLayout {
    rows: usize,
    cols: usize,
    slots: Vec<Vec<String>>,
}

fn main() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .context("missing tools directory")?
        .parent()
        .context("missing repository root")?
        .to_path_buf();

    let core_path = root.join("continuum").join("core").join("layers.toml");
    let matrix_dir = root.join("continuum").join("matrix");
    let generated_dir = root.join("continuum").join("generated");
    let keyboard_profile_dir = root.join("profiles").join("keyboard");

    let core: CoreToml = load_toml(&core_path)?;

    let slot_order = core.core.slot_order;
    let layer_order = core.core.layer_order;
    let raw_layers = core.layers;

    let mut resolved: HashMap<String, Vec<String>> = HashMap::new();
    for layer_name in &layer_order {
        let actions =
            resolve_layer_actions(layer_name, &raw_layers, &mut resolved, &mut HashSet::new())?;
        if actions.len() != slot_order.len() {
            bail!(
                "Layer {} has {} actions, expected {} from slot_order",
                layer_name,
                actions.len(),
                slot_order.len()
            );
        }
    }

    let slot_set: HashSet<&str> = slot_order.iter().map(String::as_str).collect();
    fs::create_dir_all(&generated_dir).context("failed to create continuum/generated")?;

    let mut matrix_paths = Vec::new();
    for entry in fs::read_dir(&matrix_dir).context("failed to read continuum/matrix")? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|v| v.to_str()) == Some("toml") {
            matrix_paths.push(path);
        }
    }
    matrix_paths.sort();

    let layout_section_start_re =
        Regex::new(r"(?m)^\[layout\]\r?\n").expect("layout section start regex must compile");
    let table_section_start_re =
        Regex::new(r"(?m)^\[").expect("table section start regex must compile");

    for matrix_path in matrix_paths {
        let matrix: MatrixToml = load_toml(&matrix_path)?;
        let family = matrix.meta.family;
        let rows = matrix.layout.rows;
        let cols = matrix.layout.cols;
        let slots = matrix.layout.slots;

        if slots.len() != rows {
            bail!("{}: rows mismatch", matrix_path.display());
        }
        if slots.iter().any(|row| row.len() != cols) {
            bail!("{}: cols mismatch", matrix_path.display());
        }

        let mut generated_layers: Vec<Vec<Vec<String>>> = Vec::new();
        for layer_name in &layer_order {
            let actions = resolved
                .get(layer_name)
                .context("resolved layer missing unexpectedly")?;
            let by_slot: HashMap<&str, &str> = slot_order
                .iter()
                .map(String::as_str)
                .zip(actions.iter().map(String::as_str))
                .collect();

            let mut layer_matrix: Vec<Vec<String>> = Vec::new();
            for row in &slots {
                let mut out_row: Vec<String> = Vec::new();
                for cell in row {
                    if matches!(cell.as_str(), "" | "__" | "No" | "NO") {
                        out_row.push("No".to_owned());
                    } else if slot_set.contains(cell.as_str()) {
                        let value = by_slot.get(cell.as_str()).with_context(|| {
                            format!("{}: missing slot '{}'", matrix_path.display(), cell)
                        })?;
                        out_row.push((*value).to_owned());
                    } else {
                        bail!("{}: unknown slot '{}'", matrix_path.display(), cell);
                    }
                }
                layer_matrix.push(out_row);
            }

            generated_layers.push(layer_matrix);
        }

        let generated_layout_section = render_layout_section(rows, cols, &generated_layers, "\n");
        let generated_path = generated_dir.join(format!("{}.toml", family));
        let generated_content = format!(
            "# Auto-generated by tools/generate_continuum_layers/src/main.rs\n# Source core: continuum/core/layers.toml\n# Source map: continuum/matrix/{family}.toml\n\n{generated_layout_section}"
        );
        fs::write(&generated_path, generated_content)
            .with_context(|| format!("failed to write {}", generated_path.display()))?;

        let profile_path = keyboard_profile_dir.join(format!("{}.toml", family));
        if !profile_path.exists() {
            bail!("Missing keyboard profile for family: {}", family);
        }

        let profile_text = fs::read_to_string(&profile_path)
            .with_context(|| format!("failed to read {}", profile_path.display()))?;
        let profile_newline = detect_newline(&profile_text);
        let profile_layout_section =
            render_layout_section(rows, cols, &generated_layers, profile_newline);
        let (layout_start, layout_end) = find_layout_section_range(
            &profile_text,
            &layout_section_start_re,
            &table_section_start_re,
        )
        .with_context(|| format!("Cannot find [layout] section in {}", profile_path.display()))?;
        let updated = format!(
            "{}{}{}",
            &profile_text[..layout_start],
            profile_layout_section,
            &profile_text[layout_end..]
        );
        fs::write(&profile_path, updated)
            .with_context(|| format!("failed to write {}", profile_path.display()))?;

        println!(
            "Generated {} and patched profiles/keyboard/{}.toml",
            generated_path.display(),
            family
        );
    }

    Ok(())
}

fn load_toml<T: DeserializeOwned>(path: &Path) -> Result<T> {
    let text =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    toml::from_str(&text).with_context(|| format!("failed to parse {}", path.display()))
}

fn resolve_layer_actions(
    layer_name: &str,
    raw_layers: &HashMap<String, Value>,
    cache: &mut HashMap<String, Vec<String>>,
    stack: &mut HashSet<String>,
) -> Result<Vec<String>> {
    if let Some(actions) = cache.get(layer_name) {
        return Ok(actions.clone());
    }

    if !stack.insert(layer_name.to_owned()) {
        bail!("Cycle detected while resolving layer alias: {}", layer_name);
    }

    let raw = raw_layers
        .get(layer_name)
        .with_context(|| format!("Layer '{}' not found", layer_name))?;

    let actions = match raw {
        Value::String(alias) if alias.starts_with('@') => {
            let target = &alias[1..];
            resolve_layer_actions(target, raw_layers, cache, stack)?
        }
        Value::Array(values) => values
            .iter()
            .map(value_to_action)
            .collect::<Result<Vec<_>>>()?,
        other => {
            bail!(
                "Unsupported layer payload for {}: {}",
                layer_name,
                toml_type_name(other)
            )
        }
    };

    stack.remove(layer_name);
    cache.insert(layer_name.to_owned(), actions.clone());
    Ok(actions)
}

fn value_to_action(value: &Value) -> Result<String> {
    match value {
        Value::String(v) => Ok(v.clone()),
        Value::Integer(v) => Ok(v.to_string()),
        Value::Float(v) => Ok(v.to_string()),
        Value::Boolean(v) => Ok(v.to_string()),
        other => bail!("Unsupported action value type: {}", toml_type_name(other)),
    }
}

fn toml_type_name(value: &Value) -> &'static str {
    match value {
        Value::String(_) => "string",
        Value::Integer(_) => "integer",
        Value::Float(_) => "float",
        Value::Boolean(_) => "boolean",
        Value::Datetime(_) => "datetime",
        Value::Array(_) => "array",
        Value::Table(_) => "table",
    }
}

fn render_layout_section(
    rows: usize,
    cols: usize,
    layer_actions: &[Vec<Vec<String>>],
    newline: &str,
) -> String {
    let mut lines = vec![
        "[layout]".to_owned(),
        format!("rows = {}", rows),
        format!("cols = {}", cols),
        format!("layers = {}", layer_actions.len()),
        "keymap = [".to_owned(),
    ];

    for layer in layer_actions {
        lines.push("    [".to_owned());
        for row in layer {
            let cells = row
                .iter()
                .map(|cell| format!("\"{}\"", cell))
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(format!("        [{}],", cells));
        }
        lines.push("    ],".to_owned());
    }

    lines.push("]".to_owned());
    format!("{}{}", lines.join(newline), newline)
}

fn detect_newline(content: &str) -> &'static str {
    if content.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    }
}

fn find_layout_section_range(
    profile_text: &str,
    layout_section_start_re: &Regex,
    table_section_start_re: &Regex,
) -> Option<(usize, usize)> {
    let layout_start_match = layout_section_start_re.find(profile_text)?;
    let start = layout_start_match.start();
    let search_from = layout_start_match.end();
    let end = table_section_start_re
        .find(&profile_text[search_from..])
        .map(|m| search_from + m.start())
        .unwrap_or(profile_text.len());
    Some((start, end))
}
