#!/usr/bin/env python3
"""Generate RMK keyboard profile layouts from canonical Continuum core data."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE_PATH = ROOT / "continuum" / "core" / "layers.toml"
MATRIX_DIR = ROOT / "continuum" / "matrix"
GENERATED_DIR = ROOT / "continuum" / "generated"
KEYBOARD_PROFILE_DIR = ROOT / "profiles" / "keyboard"

LAYOUT_SECTION_RE = re.compile(r"(?ms)^\[layout\]\n.*?(?=^\[|\Z)")


def load_toml(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def resolve_layer_actions(layer_name: str, raw_layers: dict, cache: dict[str, list[str]], stack: set[str]) -> list[str]:
    if layer_name in cache:
        return cache[layer_name]

    if layer_name in stack:
        raise ValueError(f"Cycle detected while resolving layer alias: {layer_name}")

    stack.add(layer_name)
    raw = raw_layers[layer_name]
    if isinstance(raw, str) and raw.startswith("@"):
        target = raw[1:]
        actions = resolve_layer_actions(target, raw_layers, cache, stack)
    elif isinstance(raw, list):
        actions = [str(v) for v in raw]
    else:
        raise ValueError(f"Unsupported layer payload for {layer_name}: {type(raw)}")

    stack.remove(layer_name)
    cache[layer_name] = actions
    return actions


def render_layout_section(rows: int, cols: int, layer_actions: list[list[list[str]]]) -> str:
    lines: list[str] = [
        "[layout]",
        f"rows = {rows}",
        f"cols = {cols}",
        f"layers = {len(layer_actions)}",
        "keymap = [",
    ]

    for layer in layer_actions:
        lines.append("    [")
        for row in layer:
            cells = ", ".join(f'"{cell}"' for cell in row)
            lines.append(f"        [{cells}],")
        lines.append("    ],")

    lines.append("]")
    return "\n".join(lines) + "\n"


def main() -> None:
    core = load_toml(CORE_PATH)
    slot_order = [str(x) for x in core["core"]["slot_order"]]
    layer_order = [str(x) for x in core["core"]["layer_order"]]
    raw_layers = core["layers"]

    resolved: dict[str, list[str]] = {}
    for layer_name in layer_order:
        actions = resolve_layer_actions(layer_name, raw_layers, resolved, set())
        if len(actions) != len(slot_order):
            raise ValueError(
                f"Layer {layer_name} has {len(actions)} actions, expected {len(slot_order)} from slot_order"
            )

    slot_set = set(slot_order)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    for matrix_path in sorted(MATRIX_DIR.glob("*.toml")):
        matrix = load_toml(matrix_path)
        family = str(matrix["meta"]["family"])
        rows = int(matrix["layout"]["rows"])
        cols = int(matrix["layout"]["cols"])
        slots = [[str(cell) for cell in row] for row in matrix["layout"]["slots"]]

        if len(slots) != rows:
            raise ValueError(f"{matrix_path}: rows mismatch")
        for row in slots:
            if len(row) != cols:
                raise ValueError(f"{matrix_path}: cols mismatch")

        generated_layers: list[list[list[str]]] = []
        for layer_name in layer_order:
            actions = resolved[layer_name]
            by_slot = dict(zip(slot_order, actions))
            layer_matrix: list[list[str]] = []

            for row in slots:
                out_row: list[str] = []
                for cell in row:
                    if cell in {"", "__", "No", "NO"}:
                        out_row.append("No")
                    elif cell in slot_set:
                        out_row.append(by_slot[cell])
                    else:
                        raise ValueError(f"{matrix_path}: unknown slot '{cell}'")
                layer_matrix.append(out_row)

            generated_layers.append(layer_matrix)

        layout_section = render_layout_section(rows, cols, generated_layers)

        generated_path = GENERATED_DIR / f"{family}.toml"
        generated_content = (
            "# Auto-generated by tools/generate_continuum_layers.py\n"
            f"# Source core: continuum/core/layers.toml\n"
            f"# Source map: continuum/matrix/{family}.toml\n\n"
            f"{layout_section}"
        )
        generated_path.write_text(generated_content, encoding="utf-8")

        profile_path = KEYBOARD_PROFILE_DIR / f"{family}.toml"
        if not profile_path.exists():
            raise FileNotFoundError(f"Missing keyboard profile for family: {family}")

        profile_text = profile_path.read_text(encoding="utf-8")
        if not LAYOUT_SECTION_RE.search(profile_text):
            raise ValueError(f"Cannot find [layout] section in {profile_path}")

        updated = LAYOUT_SECTION_RE.sub(layout_section, profile_text, count=1)
        profile_path.write_text(updated, encoding="utf-8")

        print(f"Generated {generated_path} and patched profiles/keyboard/{family}.toml")


if __name__ == "__main__":
    main()